# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default="Say'n Hello!\nWaiting for new posts"),
        ),
    ]
